Network UPS Tools website
=========================

This repository contains the scripts needed to generate the
http://www.networkupstools.org[NUT website]. Since it was originally part of
the https://github.com/networkupstools/nut/[NUT source tree], it shares some
history, and you can save some bandwidth if you already have a copy of the NUT
repository downloaded:

----
$ git clone --reference /path/to/nut https://github.com/networkupstools/nut-website.git
----

Once you have cloned the nut-website repository, you can initialize the
submodules, and pull your copy of NUT into the website tree as well:

----
$ git submodule init
Submodule 'ddl' (https://github.com/networkupstools/nut-ddl.git) registered for path 'ddl'
Submodule 'nut' (https://github.com/networkupstools/nut.git) registered for path 'nut'
$ git submodule update --reference /path/to/nut nut
...
----

Required Packages
-----------------

You will need a copy of `AsciiDoc`, `a2x` (part of AsciiDoc), and its dependencies
(`dblatex`, `xmllint`, and `xsltproc`). Current version requirements will be
listed in the output of the `./configure` script. To build the Hardware
Compatibility List (HCL) page, you will need either the `simplejson` or `json`
Python module (the json module that comes with Python 2.7 will work) and the
`lxml` module. You will also need `autoconf` and `automake`, and possibly
`libtool` since the NUT module uses it.

The `source-highlight` package is optional, but if available, will be used by
AsciiDoc for syntax highlighting of examples.

GNU `make` and GNU `coreutils` are recommended, but if you see any remaining
non-portable constructs in the Makefiles, please let us know.

Building
--------

----
$ ./autogen.sh && ./configure && make
----

NOTE: There are currently some issues with parallel builds.
Please run `make` sequentially for the time being.

The root of the website will be in the `output/` directory, if all goes well.

Publishing
----------

NOTE: These are internal notes for the maintainers.

The build result is published to the
https://github.com/networkupstools/networkupstools-master.github.io[NUT github.io master site repository]
as well as news maintenance on
https://github.com/networkupstools/networkupstools.github.io[NUT github.io latest-release site repository]

Hence, the rolling master site publication is as easy as:

----
$ git clone https://github.com/networkupstools/networkupstools-master.github.io
$ rsync -avPHK ./output/* /path/to/networkupstools-master.github.io/
----

Release site publication is much less frequent. It follows the master
site guideline when making a release, but only requires updating the
`index.html` file when `news.txt` is updated, as noted below.

NOTE: Be careful to use `git mergetool -y` to merge the updates from
a newly generated `index.html` into the release site, to keep intact
the title (marked with comments) which specifies the type of site.

----
$ git clone https://github.com/networkupstools/networkupstools.github.io
$ cp -R ./output/index.html /path/to/networkupstools.github.io/
$ (cd /path/to/networkupstools.github.io/ && git mergetool -y)
----


Updates
-------

If you only have a small patch (fixing a typo or wording), don't feel obliged
to install all of the dependencies just to test it. Feel free to create a pull
request on this repository, or send the patch as an attachment to
the http://www.networkupstools.org/support.html#_mailing_lists[nut-upsdev list]
and we will submit it to the
http://buildbot.networkupstools.org/public/nut/builders/Debian-website[Buildbot]
queue. Buildbot publishes its results at http://new.networkupstools.org and
the contents of that site will be copied to http://www.networkupstools.org
for the next NUT release.
